apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  labels:
    service: ipfs
    version: 0.4.9
  name: ipfs
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        service: ipfs
    spec:
      containers:
      - image: ipfs/go-ipfs:latest
        name: ipfs
        volumeMounts:
          - mountPath: /data/ipfs
            name: ipfs-data
        resources:
          requests:
            memory: "1Gi"
        ports:
          - name: swarm
            containerPort: 4001
          - name: api
            containerPort: 5001
          - name: web
            containerPort: 8080
          - name: swarm-ws
            containerPort: 8081
        readinessProbe:
          httpGet:
            port: 8080
            path: /ipfs/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/quick-start
      restartPolicy: Always
      volumes:
        - name: ipfs-data
          gcePersistentDisk:
            pdName: ipfs-data
            fsType: ext4
