apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ipfs-ingress
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - ipfs.greyh.at
      secretName: ipfs-tls
  defaultBackend:
    service:
      name: ipfs
      port:
        number: 100
  rules:
    - host: ipfs.greyh.at
      http:
        paths:
          - backend:
              service:
                name: ipfs
                port:
                  number: 100
            path: /
            pathType: ImplementationSpecific
