apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ipfs-ingress
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - ipfs.greyh.at
    secretName: ipfs-tls
  defaultBackend:
    service:
      name: ipfs
      port:
        number: 100
  rules:
  - host: ipfs.greyh.at
    http:
      paths:
      - path: /ipfs/QmQECm1yUgKh7oQg2syCFo5BLvhFSSH9m95fw41b3GTrXV
        pathType: ImplementationSpecific
        backend:
          service:
            name: ipfs
            port:
              number: 100
      - path: /ipfs/QmXkBQJrMKkCKNbwv4m5xtnqwU9Sq7kucPigvZW8mWxcrv
        pathType: ImplementationSpecific
        backend:
          service:
            name: ipfs
            port:
              number: 100
      - path: /ipfs/QmZQFi5kiY1cAu6hEpLCEaAZ3FX1CtmFVtE8DiLvkYNg62
        pathType: ImplementationSpecific
        backend:
          service:
            name: ipfs
            port:
              number: 100
