apiVersion: v1
kind: Service
metadata:
  name: ipfs-swarm
  namespace: default
  annotations:
    cloud.google.com/network-tier: Standard
spec:
  ports:
    - name: swarm
      port: 4001
      targetPort: 4001
    - name: websockets
      port: 8081
      targetPort: 8081
  selector:
    service: ipfs
  type: LoadBalancer
  externalTrafficPolicy: Local
